import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import AdSense from "@/components/AdSense";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentYear = new Date().getFullYear();

  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7306192465226218"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50 flex flex-col`}
      >
        <Navbar />
        
        <div className="max-w-7xl mx-auto w-full px-4">
          <AdSense slot="1234567890" type="leaderboard" />
        </div>

        <div className="flex-grow flex flex-col md:flex-row max-w-7xl mx-auto w-full gap-12 px-4">
          <main className="flex-grow min-w-0">{children}</main>
          
          <aside className="hidden lg:block w-[300px] shrink-0">
            <div className="sticky top-24">
              <AdSense slot="0987654321" type="rectangle" />
            </div>
          </aside>
        </div>

        <footer className="border-t py-8 mt-auto text-gray-500">
          <div className="max-w-7xl mx-auto px-4 text-center text-sm flex flex-col md:flex-row justify-center items-center gap-4">
            <span suppressHydrationWarning>© {currentYear} DevToolbox. Built for speed and privacy.</span>
            <div className="flex gap-4">
              <Link href="/privacy" className="hover:text-black">Privacy Policy</Link>
              <Link href="/about" className="hover:text-black">About</Link>
              <Link href="/contact" className="hover:text-black">Contact</Link>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
// Deploy Trigger: Sat Feb 14 18:02:47 UTC 2026
